### PR TITLE
Update configure.sh

### PR DESCRIPTION
**Pull request by foeroyingur**
Correct version in configure.sh

### CODE REVIEW

**Comment by foeroyingur** [comment]
@cla-bot check

**Comment by g-mathias** [comment]
Could you also set the execution bits on scripts/configure.sh while you ar at it?

**Comment by foeroyingur** [comment]
Done

**Review by g-mathias — APPROVED** [review]
I guess typos and trivial bugfixes are OK at this stage. For larger changes we will have to set up a proper review process, see #5

**Pull request merged**
